# Generated by Django 3.1.6 on 2021-02-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Domain', models.CharField(max_length=255)),
                ('IPs', models.CharField(max_length=255)),
            ],
        ),
    ]
